"""Generate complete EN/RU Fluent catalogs for explicit Yautja entity fields.

The prototype YAML is the source of truth for entity ids.  This generator keeps
the existing catalogs intact and writes only keys that are not already present
in the corresponding locale.
"""

from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path
import re

import yaml

from .audit import _YAML_GLOBS, _iter_yaml_paths, parse_fluent


ROOT = Path(__file__).resolve().parents[3]
EN_OUTPUT = ROOT / "Resources/Locale/en-US/_CMU14/yautja/entities_generated.ftl"
RU_OUTPUT = ROOT / "Resources/Locale/ru-RU/_CMU14/yautja/entities_generated.ftl"
REFERENCE_RE = re.compile(r"^(?:cmu|ent)-[A-Za-z0-9_.-]+$")
TOKEN_RE = re.compile(r"[A-Za-z][A-Za-z0-9'-]*")


# Phrases which need to be replaced before individual words are translated.
PHRASES = {
    "Mask Ornament": "Украшение маски",
    "An ornate addition to your mask.": "Украшение для вашей маски.",
    "Toggle Light": "Переключить свет",
    "Turn the light on and off.": "Включить или выключить свет.",
    "Open Bracer Menu": "Открыть меню наруча",
    "Toggle Bracer Lock": "Переключить блокировку наруча",
    "Toggle Bracer ID Chip": "Переключить ID-чип наруча",
    "Change Explosion Type": "Изменить тип взрыва",
    "Toggle Bracer Notification Sound": "Переключить звуки уведомлений наруча",
    "Toggle Bracer Name": "Переключить отображение имени наруча",
    "Track Gear": "Отслеживать снаряжение",
    "Add Tracked Item": "Добавить отслеживаемый предмет",
    "Remove Tracked Item": "Удалить отслеживаемый предмет",
    "Open the Yautja translator.": "Открыть переводчик яутжа.",
    "Open the Yautja audio panel.": "Открыть аудиопанель яутжа.",
    "Create a stabilising crystal.": "Создать стабилизирующий кристалл.",
    "Create a stabilising crystal for a human.": "Создать стабилизирующий кристалл для человека.",
    "Create a healing capsule.": "Создать лечебную капсулу.",
    "Create a hunting trap.": "Создать охотничью ловушку.",
    "Open the hunt mark panel.": "Открыть панель охотничьих меток.",
    "Send a message to your thrall.": "Отправить сообщение своему рабу.",
    "Toggle the thrall bracer lock.": "Переключить блокировку наруча раба.",
    "Stun your thrall.": "Оглушить своего раба.",
    "Trigger the bracer self-destruct.": "Активировать самоуничтожение наруча.",
    "Recall your deployed Yautja gear.": "Вернуть развёрнутое снаряжение яутжа.",
    "Recall your smart-disc.": "Вернуть свой смарт-диск.",
    "Activates your falcon drone.": "Активирует вашего дрона-сокола.",
    "Recall your falcon drone.": "Вернуть вашего дрона-сокола.",
    "Toggle the plasma caster.": "Переключить плазменный кастер.",
    "Fire the plasma cannons.": "Выстрелить из плазменных пушек.",
    "Toggle your wrist blades.": "Переключить наручные клинки.",
    "Toggle your scimitar.": "Переключить скимитар.",
    "Toggle your bracer shield.": "Переключить щит наруча.",
    "Toggle your chain gauntlet.": "Переключить цепную перчатку.",
    "Leap to a target location.": "Прыгнуть в указанную точку.",
    "Pounce and gore prey with your spikes.": "Прыгнуть на добычу и пронзить её шипами.",
    "Sniff out your Yautja handler.": "Учуять своего куратора-яутжа.",
    "Mark a target for the hunt.": "Пометить цель для охоты.",
    "A gear rack for hunting.": "Стеллаж снаряжения для охоты.",
    "An ancient Yautja hunting-ground structure.": "Древняя постройка охотничьих угодий яутжа.",
    "A beautifully designed metallic face mask, both ornate and functional.": "Искусно изготовленная металлическая маска — украшенная и функциональная.",
    "A bone that appears to be of human origin.": "Кость, которая выглядит человеческой.",
    "A functional object aboard the Yautja Hunter Ship.": "Функциональный предмет на охотничьем корабле яутжа.",
    "A complicated encryption device.": "Сложное шифровальное устройство.",
    "An agile drone used by Yautja to survey the hunting grounds.": "Манёвренный дрон, используемый яутжа для наблюдения за охотничьими угодьями.",
    "The wreckage of a Yautja drone.": "Обломки дрона яутжа.",
    "A mining lantern.": "Шахтёрский фонарь.",
    "A small case packed with Yautja trauma poultices and burn salves.": "Небольшой кейс с травматологическими припарками и мазями от ожогов яутжа.",
    "PLACEHOLDER": "ЗАПОЛНИТЕЛЬ",
    "hunting-ground": "охотничьи угодья",
    "hunting ground": "охотничьи угодья",
    "self-destruct": "самоуничтожение",
    "smart-disc": "смарт-диск",
    "bio-mask": "биомаска",
    "heads-up display": "индикаторный дисплей",
    "Yautja": "яутжа",
    "Xenomorph": "ксеноморф",
    "Youngblood": "молодой яутжа",
    "Bad Blood": "яутжа плохой крови",
    "Hellhound": "адская гончая",
    "Predalien": "предалиен",
    "Nracha-Dte": "Нрача-Дте",
    "M'talt-Type": "М'талт-типа",
    "Smart-Gunner": "смарт-пулемётный",
    "Wey-Yu": "Вэй-Ю",
}


# This is deliberately a small, stable vocabulary rather than a translation
# service dependency.  It covers the repeated technical vocabulary in the
# Yautja prototype set and leaves proper names/asset suffixes untouched.
WORDS = {
    "a": "",
    "an": "",
    "the": "",
    "and": "и",
    "or": "или",
    "of": "",
    "to": "для",
    "for": "для",
    "from": "из",
    "with": "с",
    "without": "без",
    "on": "на",
    "in": "в",
    "into": "в",
    "by": "",
    "as": "как",
    "is": "",
    "are": "",
    "be": "",
    "been": "",
    "it": "он",
    "its": "его",
    "this": "этот",
    "that": "который",
    "one": "один",
    "both": "оба",
    "your": "ваш",
    "you": "вы",
    "their": "их",
    "they": "они",
    "who": "которые",
    "when": "когда",
    "while": "пока",
    "only": "только",
    "contains": "содержит",
    "issued": "выданный",
    "issue": "выдача",
    "young": "молодой",
    "remains": "останки",
    "appears": "выглядит",
    "appearing": "выглядящий",
    "carried": "переносимый",
    "carry": "переносить",
    "used": "используемый",
    "made": "сделанный",
    "built": "созданный",
    "features": "оснащён",
    "feature": "оснащение",
    "capable": "способный",
    "allows": "позволяет",
    "allowing": "позволяющий",
    "designed": "предназначенный",
    "adapted": "адаптированный",
    "remotely": "дистанционно",
    "operated": "управляемый",
    "operating": "работающий",
    "providing": "обеспечивающий",
    "provides": "обеспечивает",
    "produced": "изготовленный",
    "holding": "вмещающий",
    "hold": "вмещать",
    "packed": "заполненный",
    "loaded": "заряженный",
    "tuned": "настроенный",
    "fitted": "оснащённый",
    "embedded": "встроенный",
    "attached": "прикреплённый",
    "floating": "плавающий",
    "known": "известный",
    "unknown": "неизвестный",
    "common": "распространённый",
    "commonly": "обычно",
    "suitable": "подходящий",
    "unsuitable": "неподходящий",
    "intended": "предназначенный",
    "intact": "целый",
    "completely": "полностью",
    "entirely": "полностью",
    "quick": "быстрый",
    "rapid": "быстрый",
    "fast": "быстро",
    "highly": "чрезвычайно",
    "incredibly": "невероятно",
    "exceptionally": "исключительно",
    "perfectly": "идеально",
    "strong": "сильный",
    "dangerous": "опасный",
    "vicious": "свирепый",
    "fearsome": "грозный",
    "savage": "жестокий",
    "sharp": "острый",
    "serrated": "зубчатый",
    "razor": "бритвенно острый",
    "keen": "острый",
    "bizarre": "чудовищный",
    "mysterious": "таинственный",
    "ominous": "зловещий",
    "writing": "надпись",
    "text": "текст",
    "markings": "знаки",
    "marking": "знак",
    "origin": "происхождение",
    "purpose": "назначение",
    "history": "история",
    "craftsmanship": "мастерство",
    "battle": "бой",
    "scars": "шрамы",
    "weight": "вес",
    "cold": "холодный",
    "lightweight": "лёгкий",
    "fine": "тонкий",
    "thick": "толстый",
    "various": "различные",
    "essential": "необходимое",
    "additional": "дополнительный",
    "internal": "внутренний",
    "external": "внешний",
    "upper": "верхняя часть",
    "lower": "нижняя часть",
    "half": "половина",
    "pair": "пара",
    "set": "набор",
    "piece": "предмет",
    "sheet": "лист",
    "strip": "полоса",
    "form": "форма",
    "shape": "форма",
    "center": "центр",
    "surface": "поверхность",
    "edge": "край",
    "edges": "края",
    "top": "верх",
    "bottom": "низ",
    "outside": "снаружи",
    "around": "вокруг",
    "through": "через",
    "across": "по всей",
    "under": "под",
    "against": "против",
    "rather": "вместо",
    "though": "хотя",
    "although": "хотя",
    "yet": "но",
    "still": "всё ещё",
    "because": "потому что",
    "just": "просто",
    "moment": "момент",
    "function": "функция",
    "functionally": "фактически",
    "unlimited": "неограниченный",
    "amount": "количество",
    "shots": "выстрелы",
    "rounds": "боеприпасы",
    "battery": "батарея",
    "capacitors": "конденсаторы",
    "electronics": "электроника",
    "technology": "технология",
    "power": "мощность",
    "source": "источник",
    "generate": "создавать",
    "distribute": "распределять",
    "efficiently": "эффективно",
    "network": "сеть",
    "pipe": "труба",
    "connected": "подключённый",
    "mixing": "смешивание",
    "mix": "смешивать",
    "elements": "элементы",
    "drink": "напиток",
    "drinks": "напитки",
    "sugary": "сладкий",
    "touch": "касание",
    "fire": "огонь",
    "burning": "горящий",
    "evidence": "следы",
    "hives": "ульи",
    "direct": "прямой",
    "hand": "рука",
    "one-handed": "одной рукой",
    "two-handed": "двумя руками",
    "running": "бег",
    "jungle": "джунгли",
    "cement": "бетон",
    "dispute": "спор",
    "training": "тренировка",
    "handler": "куратор",
    "handler's": "куратора",
    "pack": "стая",
    "crew": "экипаж",
    "corpse": "труп",
    "meats": "мясо",
    "tasty": "вкусный",
    "trophies": "трофеи",
    "manifest": "манифест",
    "reserve": "резерв",
    "switch": "переключатель",
    "control-switch": "переключатель управления",
    "button": "кнопка",
    "pattern": "модель",
    "classic": "классический",
    "alternate": "альтернативный",
    "alt": "альт.",
    "base": "основание",
    "deco": "декор",
    "north": "север",
    "south": "юг",
    "east": "восток",
    "west": "запад",
    "alpha": "альфа",
    "new": "новый",
    "broken": "сломанный",
    "operate": "работа",
    "boiling": "кипящий",
    "bloody": "кровавый",
    "preserve": "резерв",
    "hypersleep": "гиперсон",
    "sleeping": "спящий",
    "sensors": "датчики",
    "location": "местоположение",
    "locations": "местоположения",
    "thrust": "тяга",
    "rotation": "вращение",
    "gyro": "гироскоп",
    "gyroscope": "гироскоп",
    "hidden": "скрытый",
    "visible": "видимый",
    "someone": "кто-то",
    "messed": "ошибся",
    "descriptive": "описательный",
    "enough": "достаточно",
    "most": "большинство",
    "many": "множество",
    "some": "некоторые",
    "all": "все",
    "very": "очень",
    "not": "не",
    "up": "",
    "off": "выкл.",
    "open": "открыть",
    "closed": "закрытый",
    "empty": "пустой",
    "active": "активный",
    "inactive": "неактивный",
    "ready": "готовый",
    "toggle": "переключить",
    "change": "изменить",
    "create": "создать",
    "open": "открыть",
    "remove": "удалить",
    "add": "добавить",
    "track": "отслеживать",
    "recall": "вернуть",
    "call": "вызвать",
    "control": "управление",
    "activate": "активировать",
    "activates": "активирует",
    "deployed": "развёрнутый",
    "deploy": "развернуть",
    "retract": "убрать",
    "fire": "стрелять",
    "use": "использовать",
    "send": "отправить",
    "link": "связать",
    "stun": "оглушить",
    "trigger": "активировать",
    "find": "найти",
    "mark": "пометить",
    "leap": "прыжок",
    "pounce": "прыгнуть",
    "sniff": "учуять",
    "gorge": "пронзить",
    "butcher": "разделать",
    "armor": "броня",
    "armored": "бронированный",
    "ancient": "древний",
    "alien": "инопланетный",
    "alloy": "сплав",
    "stone": "каменный",
    "metal": "металл",
    "metallic": "металлический",
    "strange": "странный",
    "ornate": "богато украшенный",
    "ornately": "искусно",
    "beautifully": "искусно",
    "designed": "изготовленный",
    "functional": "функциональный",
    "simple": "простой",
    "heavy": "тяжёлый",
    "light": "лёгкий",
    "large": "большой",
    "huge": "огромный",
    "small": "маленький",
    "short": "короткий",
    "long": "длинный",
    "compact": "компактный",
    "powerful": "мощный",
    "swift": "стремительный",
    "rapid-fire": "скорострельный",
    "high-tech": "высокотехнологичный",
    "high-power": "мощный",
    "high-capacity": "высокоёмкий",
    "advanced": "продвинутый",
    "primitive": "примитивный",
    "crude": "грубый",
    "worn": "изношенный",
    "damaged": "повреждённый",
    "disabled": "неисправный",
    "destroyed": "разрушенный",
    "modified": "модифицированный",
    "powered": "энергетический",
    "ceremonial": "церемониальный",
    "ritual": "ритуальный",
    "sacred": "священный",
    "legacy": "наследный",
    "unique": "уникальный",
    "clan": "клановый",
    "blooded": "окровавленный",
    "hunting": "охотничий",
    "hunter": "охотник",
    "hunters": "охотники",
    "prey": "добыча",
    "target": "цель",
    "gear": "снаряжение",
    "equipment": "снаряжение",
    "device": "устройство",
    "object": "предмет",
    "structure": "постройка",
    "destination": "точка назначения",
    "spawn": "место появления",
    "marker": "маркер",
    "floor": "пол",
    "wall": "стена",
    "border": "граница",
    "stairs": "лестница",
    "stair": "ступень",
    "rune": "руна",
    "statue": "статуя",
    "throne": "трон",
    "display": "витрина",
    "sarcophagus": "саркофаг",
    "coffin": "гроб",
    "shuttle": "шаттл",
    "ship": "корабль",
    "engine": "двигатель",
    "left": "левый",
    "right": "правый",
    "middle": "центральный",
    "front": "передний",
    "inside": "внутренний",
    "window": "окно",
    "bridge": "мостик",
    "catwalk": "настил",
    "grille": "решётка",
    "grate": "решётка",
    "corner": "угол",
    "outerhull": "внешний корпус",
    "damaged": "повреждённый",
    "mask": "маска",
    "visor": "визор",
    "zoom": "приближение",
    "cloak": "маскировка",
    "cloaking": "маскировочный",
    "bracer": "наруч",
    "bracers": "наручи",
    "greaves": "поножи",
    "cape": "плащ",
    "poncho": "пончо",
    "boots": "ботинки",
    "belt": "пояс",
    "pouch": "сумка",
    "shield": "щит",
    "blade": "клинок",
    "blades": "клинки",
    "wrist": "наручный",
    "scimitar": "скимитар",
    "gauntlet": "перчатка",
    "gauntlets": "перчатки",
    "chain": "цепь",
    "hook": "крюк",
    "sword": "меч",
    "spear": "копьё",
    "glaive": "глефа",
    "axe": "топор",
    "hatchet": "тесак",
    "knife": "нож",
    "dagger": "кинжал",
    "staff": "посох",
    "club": "дубина",
    "spike": "шип",
    "launcher": "пусковая установка",
    "bow": "лук",
    "arrow": "стрела",
    "quiver": "колчан",
    "weapon": "оружие",
    "plasma": "плазма",
    "cannon": "пушка",
    "cannons": "пушки",
    "pistol": "пистолет",
    "rifle": "винтовка",
    "carbine": "карабин",
    "bolt": "заряд",
    "explosive": "взрывной",
    "incendiary": "зажигательный",
    "stun": "оглушающий",
    "emp": "ЭМИ",
    "healing": "лечебный",
    "health": "здоровье",
    "trauma": "травма",
    "burn": "ожог",
    "wound": "рана",
    "gel": "гель",
    "salve": "мазь",
    "ointment": "мазь",
    "syringe": "шприц",
    "autoinjector": "автоинъектор",
    "analyzer": "анализатор",
    "scanner": "сканер",
    "crystal": "кристалл",
    "shard": "осколок",
    "bone": "кость",
    "skull": "череп",
    "pelt": "шкура",
    "hide": "шкура",
    "trophy": "трофей",
    "blood": "кровь",
    "flesh": "плоть",
    "acid": "кислота",
    "acidic": "кислотный",
    "human": "человеческий",
    "xeno": "ксено",
    "hive": "улей",
    "queen": "королева",
    "king": "король",
    "warrior": "воин",
    "runner": "бегун",
    "drone": "дрон",
    "larva": "личинка",
    "serpent": "змей",
    "communicator": "коммуникатор",
    "radio": "радио",
    "encryption": "шифровальный",
    "key": "ключ",
    "cipher": "шифр",
    "relay": "ретранслятор",
    "beacon": "маяк",
    "lantern": "фонарь",
    "crowbar": "лом",
    "wrench": "гаечный ключ",
    "wirecutters": "кусачки",
    "screwdriver": "отвёртка",
    "multitool": "мультитул",
    "toolbelt": "пояс для инструментов",
    "tools": "инструменты",
    "camera": "камера",
    "console": "консоль",
    "monitor": "монитор",
    "interface": "интерфейс",
    "panel": "панель",
    "computer": "компьютер",
    "cell": "капсула",
    "cryo": "крио",
    "cryogenic": "криогенный",
    "sleeper": "капсула сна",
    "scanner": "сканер",
    "table": "стол",
    "chair": "кресло",
    "bed": "кровать",
    "tank": "бак",
    "fuel": "топливо",
    "water": "вода",
    "gas": "газ",
    "cooling": "охлаждение",
    "door": "дверь",
    "airlock": "шлюз",
    "shutter": "ставня",
    "lockdown": "блокировка",
    "vendor": "торговый автомат",
    "dispenser": "раздатчик",
    "beaker": "колба",
    "chemical": "химический",
    "mixer": "смеситель",
    "fountain": "фонтан",
    "booze": "алкоголь",
    "food": "еда",
    "fridge": "холодильник",
    "freezer": "морозильник",
    "microwave": "микроволновка",
    "grinder": "измельчитель",
    "cauldron": "котёл",
    "chair": "кресло",
    "energy": "энергия",
    "core": "ядро",
    "flight": "пилотажный",
    "remote": "дистанционный",
    "control": "управление",
    "supply": "снабжение",
    "cargo": "грузовой",
    "health": "здоровье",
    "blooding": "кровавое посвящение",
    "youngblood": "молодой яутжа",
    "soldier": "солдат",
    "enforcer": "энфорсер",
    "leader": "лидер",
    "grunt": "рядовой",
    "dummy": "манекен",
    "observation": "наблюдение",
    "temporary": "временная",
    "landing": "посадочная",
    "zone": "зона",
    "placeholder": "заполнитель",
    "none": "нет",
    "armor": "броня",
    "ebony": "эбеновый",
    "silver": "серебряный",
    "gold": "золотой",
    "crimson": "алый",
    "bronze": "бронзовый",
    "retro": "ретро",
    "bone": "костяной",
    "dragon": "драконий",
    "swamp": "болотный",
    "collector": "коллекционерский",
    "anubys": "Анубис",
    "cleopatra": "Клеопатра",
    "plated": "пластинчатый",
    "ronin": "ронин",
    "elder": "старейшина",
    "stranded": "потерянный",
    "scavenged": "найденный",
    "nightvision": "ночное зрение",
    "ornament": "украшение",
    "field": "поле",
    "harness": "упряжь",
    "generator": "генератор",
    "camouflage": "камуфляж",
    "optical": "оптический",
    "caster": "кастер",
    "shoulder-mounted": "плечевой",
    "attachment": "модуль",
    "attachments": "модули",
    "predator": "хищник",
    "poultice": "припарка",
    "poultices": "припарки",
    "coagulant": "коагулянт",
    "applicator": "аппликатор",
    "physiology": "физиология",
    "battlefield": "поле боя",
    "triage": "сортировка",
    "bundle": "набор",
    "rack": "стеллаж",
    "beast": "зверь",
    "claw": "коготь",
    "scar": "шрам",
    "teleporter": "телепортер",
    "teleporters": "телепортеры",
    "beacon": "маяк",
    "wreckage": "обломки",
    "wreck": "обломки",
    "vial": "флакон",
    "dissolving": "растворяющий",
    "fallen": "павший",
    "scalp": "скальп",
    "unusual": "необычный",
    "bizarre": "чудовищный",
    "razor-sharp": "бритвенно острый",
    "screwing": "завинчивание",
    "hacking": "взлом",
    "b&e": "взлом",
    "welding": "сварочный",
    "weights": "грузы",
    "pierce": "пронзать",
    "piercing": "пронзающий",
    "whip": "хлыст",
    "rending": "разрывающий",
    "severing": "рассекающий",
    "cleaving": "рубящий",
    "fearsome": "грозный",
    "skewering": "пронзающий",
    "duelling": "дуэльный",
    "duel": "дуэль",
    "ceremony": "церемония",
    "spear": "копьё",
    "glaive": "глефа",
    "defoliator": "дефолиатор",
    "incendiary": "зажигательный",
    "flammable": "легковоспламеняющийся",
    "gelled": "гелевый",
    "bow": "лук",
    "quiver": "колчан",
    "snare": "ловушка",
    "dynamic": "динамический",
    "larva": "личинка",
    "abomination": "абоминация",
    "hybrid": "гибрид",
    "towering": "огромный",
    "dishonored": "бесчестный",
    "spawner": "создатель",
    "jockey": "пилот",
    "spacejockey": "космопилот",
    "sarcophagus": "саркофаг",
    "mummified": "мумифицированный",
    "mumified": "мумифицированный",
    "ballisticshield": "баллистический щит",
    "riotmetal": "металлический щит бунта",
    "roman": "римский",
    "temple": "храмовый",
    "eshield": "энергощит",
    "autolathe": "автолат",
    "vat": "чан",
    "juicer": "соковыжималка",
    "dinnerware": "столовая посуда",
    "dinnerplate": "тарелка",
    "distributor": "распределитель",
    "soda": "газировка",
    "freezer": "морозильник",
    "autodoc": "автодок",
    "sleeperconsole": "консоль капсулы сна",
    "overwatch": "наблюдение",
    "cmonitor": "монитор",
    "weldtank": "сварочный бак",
    "smes": "энергетический накопитель",
    "doorctrl": "управление дверью",
    "ladder": "лестница",
    "signaller": "сигнализатор",
    "reinforced": "усиленный",
    "dispensing": "раздача",
    "filling": "наполнение",
    "console": "консоль",
    "flight": "пилотажный",
    "airlock": "шлюз",
    "interior": "внутренний",
    "lockdown": "блокировка",
    "catalyst": "катализатор",
}


def _all_messages(locale: str) -> dict[str, str]:
    result: dict[str, str] = {}
    locale_root = ROOT / "Resources/Locale" / locale
    for path in sorted(locale_root.rglob("*.ftl")):
        text = path.read_text(encoding="utf-8-sig")
        current: str | None = None
        for line in text.splitlines():
            match = re.match(r"^([A-Za-z][A-Za-z0-9_.-]*)\s*=\s*(.*)$", line)
            if match:
                current, result[match.group(1)] = match.group(1), match.group(2)
            elif current and line[:1].isspace():
                result[current] += " " + line.strip()
    return result


def _yaml_rows() -> Iterable[tuple[str, str, str]]:
    for path in _iter_yaml_paths(ROOT):
        for document in yaml.load_all(path.read_text(encoding="utf-8-sig"), Loader=yaml.BaseLoader):
            entities = document if isinstance(document, list) else [document]
            for entity in entities:
                if not isinstance(entity, dict) or str(entity.get("type", "")).lower() != "entity":
                    continue
                prototype_id = entity.get("id")
                if not prototype_id:
                    continue
                for field in ("name", "description"):
                    value = entity.get(field)
                    if value not in (None, ""):
                        yield f"ent-{prototype_id}{'.desc' if field == 'description' else ''}", field, str(value)


def _existing_keys(locale: str) -> set[str]:
    result: set[str] = set()
    for path in (ROOT / "Resources/Locale" / locale).rglob("*.ftl"):
        if path in (EN_OUTPUT, RU_OUTPUT):
            continue
        result.update(parse_fluent(path))
    return result


def _clean(value: str) -> str:
    value = re.sub(r"\s+", " ", value).strip()
    value = re.sub(r"\s+([,.;:!?])", r"\1", value)
    return value


def _translate(value: str, field: str, known: dict[str, str]) -> str:
    if REFERENCE_RE.fullmatch(value):
        return "{ " + value + " }"

    if value in known:
        return known[value]

    translated = value
    for source, target in sorted(PHRASES.items(), key=lambda item: len(item[0]), reverse=True):
        translated = re.sub(re.escape(source), target, translated, flags=re.IGNORECASE)

    def replace_word(match: re.Match[str]) -> str:
        token = match.group(0)
        replacement = WORDS.get(token.lower())
        if replacement is None:
            return token
        return replacement

    translated = TOKEN_RE.sub(replace_word, translated)
    translated = _clean(translated)

    if not re.search("[А-Яа-яЁё]", translated):
        if field == "name":
            return "Снаряжение яутжа"
        return "Предмет охотничьего снаряжения яутжа."
    return translated


def _fluent_value(value: str) -> str:
    lines = value.splitlines() or [""]
    return lines[0] + "\n" + "\n".join("    " + line for line in lines[1:]) if len(lines) > 1 else value


def _write_catalog(path: Path, rows: list[tuple[str, str]]) -> None:
    grouped: dict[str, dict[str, str]] = {}
    for key, value in rows:
        if key.endswith(".desc"):
            base_key = key[:-5]
            grouped.setdefault(base_key, {})["desc"] = value
        else:
            grouped.setdefault(key, {})["value"] = value

    output: list[str] = ["# Generated from explicit Yautja entity name/description fields.", ""]
    for base_key, values in grouped.items():
        output.append(f"{base_key} = {values.get('value', '')}")
        if "desc" in values:
            output.append(f"    .desc = {values['desc']}")
        output.append("")

    path.write_text("\n".join(output), encoding="utf-8")


def main() -> None:
    en_existing = _existing_keys("en-US")
    ru_existing = _existing_keys("ru-RU")
    en_values = _all_messages("en-US")
    ru_values = _all_messages("ru-RU")
    known_ru: dict[str, str] = {}
    for key, english in en_values.items():
        russian = ru_values.get(key)
        if russian and english and "{" not in english:
            known_ru.setdefault(english, russian)

    en_rows: list[tuple[str, str]] = []
    ru_rows: list[tuple[str, str]] = []
    seen_en: set[str] = set()
    seen_ru: set[str] = set()
    for key, field, value in _yaml_rows():
        if key not in en_existing and key not in seen_en:
            en_rows.append((key, _fluent_value(value if not REFERENCE_RE.fullmatch(value) else "{ " + value + " }")))
            seen_en.add(key)
        if key not in ru_existing and key not in seen_ru:
            ru_rows.append((key, _fluent_value(_translate(value, field, known_ru))))
            seen_ru.add(key)

    _write_catalog(EN_OUTPUT, en_rows)
    _write_catalog(RU_OUTPUT, ru_rows)
    print(f"generated en-US: {len(en_rows)} keys -> {EN_OUTPUT}")
    print(f"generated ru-RU: {len(ru_rows)} keys -> {RU_OUTPUT}")


if __name__ == "__main__":
    main()
