using Content.Client.UserInterface.Controls;
using Content.Shared._RMC14.Onboarding;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Onboarding;

[GenerateTypedNameReferences]
public sealed partial class RMCOnboardingWindow : FancyWindow
{
    public event Action<RMCOnboardingTrack>? TrackSelected;
    public event Action? Skipped;

    public RMCOnboardingWindow()
    {
        RobustXamlLoader.Load(this);
        SkipButton.OnPressed += _ => Skipped?.Invoke();
    }

    public void SetTracks(IReadOnlyList<RMCOnboardingTrackStatus> tracks)
    {
        TrackList.RemoveAllChildren();

        foreach (var status in tracks)
        {
            var track = status.Track;
            var container = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 10),
            };

            var button = new Button
            {
                Text = Loc.GetString(status.Completed
                    ? "rmc-onboarding-window-replay"
                    : "rmc-onboarding-window-start"),
                HorizontalExpand = true,
                MinHeight = 36,
                Disabled = !status.Available,
            };

            container.AddChild(new Label
            {
                Text = Loc.GetString(track.LocName()),
                StyleClasses = { "LabelHeading" },
                HorizontalExpand = true,
                Margin = new Thickness(8, 3, 8, 0),
            });

            container.AddChild(new Label
            {
                Text = Loc.GetString(track.LocDescription()),
                HorizontalExpand = true,
                Margin = new Thickness(8, 3, 8, 0),
            });

            container.AddChild(new Label
            {
                Text = Loc.GetString(status.Available
                    ? status.Completed
                        ? "rmc-onboarding-status-completed"
                        : "rmc-onboarding-status-available"
                    : "rmc-onboarding-status-development"),
                HorizontalExpand = true,
                Margin = new Thickness(8, 3, 8, 0),
            });

            button.Margin = new Thickness(0, 8, 0, 0);
            button.OnPressed += _ => TrackSelected?.Invoke(track);
            container.AddChild(button);

            TrackList.AddChild(container);
        }
    }
}
