using Content.Client.UserInterface.Controls;
using Content.Shared._RMC14.Onboarding;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Onboarding;

[GenerateTypedNameReferences]
public sealed partial class RMCOnboardingTaskWindow : FancyWindow
{
    public event Action? ExitRequested;

    public RMCOnboardingTaskWindow()
    {
        RobustXamlLoader.Load(this);
        ExitButton.OnPressed += _ => ExitRequested?.Invoke();
    }

    public void SetTask(RMCOnboardingTaskEvent task)
    {
        ProgressLabel.Text = Loc.GetString("rmc-onboarding-task-progress",
            ("step", task.Step),
            ("count", task.StepCount));
        TitleLabel.Text = Loc.GetString(task.Title);
        DescriptionLabel.SetMessage(Loc.GetString(task.Description));
        HintLabel.Text = Loc.GetString(task.Hint);
    }
}
