using System;
using Content.Shared._RMC14.Xenonids.Boxer;
using Content.Shared.Actions;
using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using NUnit.Framework;

namespace Content.Tests.Shared._RMC14.Xenonids;

[TestFixture]
public sealed class XenoBoxerRulesTest
{
    [Test]
    public void AddKoClampsToMaximum()
    {
        Assert.That(XenoBoxerRules.AddKo(14.5f, 1f), Is.EqualTo(XenoBoxerRules.MaxKo));
        Assert.That(XenoBoxerRules.AddKo(3f, 1f), Is.EqualTo(4f));
    }

    [Test]
    public void TargetChangeIsDetectedOnlyForDifferentTargets()
    {
        var first = new EntityUid(1);
        var second = new EntityUid(2);

        Assert.That(XenoBoxerRules.IsDifferentTarget(null, first), Is.False);
        Assert.That(XenoBoxerRules.IsDifferentTarget(first, first), Is.False);
        Assert.That(XenoBoxerRules.IsDifferentTarget(first, second), Is.True);
    }

    [Test]
    public void KoExpiresAtFiveSeconds()
    {
        Assert.That(XenoBoxerRules.IsKoExpired(TimeSpan.FromSeconds(4.99), TimeSpan.Zero), Is.False);
        Assert.That(XenoBoxerRules.IsKoExpired(TimeSpan.FromSeconds(5), TimeSpan.Zero), Is.True);
    }

    [TestCase(0, XenoBoxerUppercutStage.None)]
    [TestCase(0.99f, XenoBoxerUppercutStage.None)]
    [TestCase(1, XenoBoxerUppercutStage.Damage)]
    [TestCase(2.99f, XenoBoxerUppercutStage.Damage)]
    [TestCase(3, XenoBoxerUppercutStage.KnockBack)]
    [TestCase(5.99f, XenoBoxerUppercutStage.KnockBack)]
    [TestCase(6, XenoBoxerUppercutStage.KnockDown)]
    [TestCase(8.99f, XenoBoxerUppercutStage.KnockDown)]
    [TestCase(9, XenoBoxerUppercutStage.KnockOut)]
    public void UppercutStageUsesHistoricalThresholds(float ko, XenoBoxerUppercutStage expected)
    {
        Assert.That(XenoBoxerRules.GetUppercutStage(ko), Is.EqualTo(expected));
    }

    [Test]
    public void UppercutScalesDamageAndKnockbackByKo()
    {
        Assert.That(XenoBoxerRules.GetUppercutDamage(0, 15), Is.Zero);
        Assert.That(XenoBoxerRules.GetUppercutDamage(2, 15), Is.EqualTo(30));
        Assert.That(XenoBoxerRules.GetUppercutKnockBackPower(2.99f, 1), Is.Zero);
        Assert.That(XenoBoxerRules.GetUppercutKnockBackPower(3, 1), Is.EqualTo(3));
    }

    [Test]
    public void UppercutKnockdownUsesQuarterSecondPerKo()
    {
        Assert.That(XenoBoxerRules.GetUppercutKnockDownDuration(5.99f), Is.EqualTo(TimeSpan.Zero));
        Assert.That(XenoBoxerRules.GetUppercutKnockDownDuration(6), Is.EqualTo(TimeSpan.FromSeconds(1.5)));
        Assert.That(XenoBoxerRules.GetUppercutKnockDownDuration(9), Is.EqualTo(TimeSpan.FromSeconds(2.25)));
    }

    [Test]
    public void UppercutHealUsesMaxHealthAndXenoMultiplier()
    {
        Assert.That(XenoBoxerRules.GetUppercutHealAmount(0, 600, 0.05f, 0.35f, false), Is.Zero);
        Assert.That(XenoBoxerRules.GetUppercutHealAmount(2, 600, 0.05f, 0.35f, false), Is.EqualTo(60));
        Assert.That(XenoBoxerRules.GetUppercutHealAmount(2, 600, 0.05f, 0.35f, true), Is.EqualTo(21));
    }

    [Test]
    public void ClearHeadConsumesOnlyForNonForcedEffects()
    {
        var charges = 1;

        Assert.That(XenoBoxerRules.TryConsumeClearHead(ref charges, forced: true), Is.False);
        Assert.That(charges, Is.EqualTo(1));
        Assert.That(XenoBoxerRules.TryConsumeClearHead(ref charges, forced: false), Is.True);
        Assert.That(charges, Is.Zero);
        Assert.That(XenoBoxerRules.TryConsumeClearHead(ref charges, forced: false), Is.False);
    }

    [Test]
    public void ClearHeadRegenerationIsDueOnlyBelowMaximum()
    {
        var next = TimeSpan.FromSeconds(15);

        Assert.That(XenoBoxerRules.IsClearHeadRegenDue(TimeSpan.FromSeconds(14.99), next, 0), Is.False);
        Assert.That(XenoBoxerRules.IsClearHeadRegenDue(next, next, 0), Is.True);
        Assert.That(XenoBoxerRules.IsClearHeadRegenDue(next, next, XenoBoxerRules.ClearHeadMaxCharges), Is.False);
        Assert.That(XenoBoxerRules.GetNextClearHeadRegenAt(next), Is.EqualTo(TimeSpan.FromSeconds(30)));
    }

    [Test]
    public void InitialClearHeadChargesAreZeroForXenoVersusXeno()
    {
        Assert.That(XenoBoxerRules.GetInitialClearHeadCharges(isXenoVersusXeno: true), Is.Zero);
        Assert.That(XenoBoxerRules.GetInitialClearHeadCharges(isXenoVersusXeno: false), Is.EqualTo(XenoBoxerRules.ClearHeadMaxCharges));
    }

    [Test]
    public void BoxerStateIsNetworkedAndAutoGenerated()
    {
        Assert.That(typeof(XenoBoxerComponent).IsDefined(typeof(NetworkedComponentAttribute), inherit: false), Is.True);
        Assert.That(typeof(XenoBoxerComponent).IsDefined(typeof(AutoGenerateComponentStateAttribute), inherit: false), Is.True);
    }

    [TestCase(typeof(XenoBoxerPunchActionEvent))]
    [TestCase(typeof(XenoBoxerJabActionEvent))]
    [TestCase(typeof(XenoBoxerUppercutActionEvent))]
    public void BoxerActionsUseEntityTargets(Type actionType)
    {
        Assert.That(typeof(EntityTargetActionEvent).IsAssignableFrom(actionType), Is.True);
    }
}
