using Content.Client.Message;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Shared.CCVar;
using Robust.Client.Animations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Animations;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        private const float BalanceRatingBottomMargin = 84f;
        private const float MinimumTerminalColumnWidth = 350f;
        private const float LeftPanelVisualPadding = 34f;
        private const float RightPanelVisualPadding = 20f;

        [Dependency] private IClientConsoleHost _consoleHost = default!;
        [Dependency] private IConfigurationManager _configuration = default!;

        private bool _rightPanelAutoCollapsed;

        private static readonly Animation TerminalCardBootAnimation = new()
        {
            Length = TimeSpan.FromSeconds(0.55),
            AnimationTracks =
            {
                new AnimationTrackControlProperty
                {
                    Property = nameof(Control.Modulate),
                    InterpolationMode = AnimationInterpolationMode.Linear,
                    KeyFrames =
                    {
                        new AnimationTrackProperty.KeyFrame(Color.Transparent, 0f),
                        new AnimationTrackProperty.KeyFrame(Color.White, 0.55f),
                    },
                },
            },
        };

        private static readonly Animation TerminalHeaderBootAnimation = new()
        {
            Length = TimeSpan.FromSeconds(1.05),
            AnimationTracks =
            {
                new AnimationTrackControlProperty
                {
                    Property = nameof(Control.Modulate),
                    InterpolationMode = AnimationInterpolationMode.Linear,
                    KeyFrames =
                    {
                        new AnimationTrackProperty.KeyFrame(Color.Transparent, 0f),
                        new AnimationTrackProperty.KeyFrame(Color.Transparent, 0.28f),
                        new AnimationTrackProperty.KeyFrame(Color.White, 0.77f),
                    },
                },
            },
        };

        private static readonly Animation TerminalActionsBootAnimation = new()
        {
            Length = TimeSpan.FromSeconds(1.65),
            AnimationTracks =
            {
                new AnimationTrackControlProperty
                {
                    Property = nameof(Control.Modulate),
                    InterpolationMode = AnimationInterpolationMode.Linear,
                    KeyFrames =
                    {
                        new AnimationTrackProperty.KeyFrame(Color.Transparent, 0f),
                        new AnimationTrackProperty.KeyFrame(Color.Transparent, 0.72f),
                        new AnimationTrackProperty.KeyFrame(Color.White, 0.93f),
                    },
                },
            },
        };

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);
            SetAnchorPreset(TerminalBackground, LayoutPreset.Wide);
            Background.Visible = false;
            PositionBalanceRatingContainer();
            CrtLobbyTheme.Apply(MainContainer);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();

            CollapseButton.OnPressed += _ => TogglePanel(false);
            ExpandButton.OnPressed += _ => TogglePanel(true);
            MainContainer.OnResized += KeepTerminalUsable;
            TerminalCard.OnResized += SyncTerminalViewport;
            RightSide.OnResized += SyncTerminalViewport;
        }

        public void StartBootSequence()
        {
            const string cardAnimation = "lobby-terminal-card-boot";
            const string headerAnimation = "lobby-terminal-header-boot";
            const string actionsAnimation = "lobby-terminal-actions-boot";

            TerminalCard.StopAnimation(cardAnimation);
            TerminalHeader.StopAnimation(headerAnimation);
            TerminalActions.StopAnimation(actionsAnimation);
            TerminalBackground.RestartBootSequence();

            var animate = StyleNano.CrtUiEnabled && !_configuration.GetCVar(CCVars.ReducedMotion);
            TerminalCard.Modulate = animate ? Color.Transparent : Color.White;
            TerminalHeader.Modulate = animate ? Color.Transparent : Color.White;
            TerminalActions.Modulate = animate ? Color.Transparent : Color.White;

            if (!animate)
                return;

            TerminalCard.PlayAnimation(TerminalCardBootAnimation, cardAnimation);
            TerminalHeader.PlayAnimation(TerminalHeaderBootAnimation, headerAnimation);
            TerminalActions.PlayAnimation(TerminalActionsBootAnimation, actionsAnimation);
        }

        public void SetRightPanelWidth(float width)
        {
            RightSide.SetWidth = width;
            KeepTerminalUsable();
            SyncTerminalViewport();
        }

        public void PositionBalanceRatingContainer()
        {
            SetAnchorAndMarginPreset(BalanceRatingContainer, LayoutPreset.BottomLeft, margin: 10);
            SetMarginTop(
                BalanceRatingContainer,
                -BalanceRatingContainer.DesiredSize.Y - BalanceRatingBottomMargin);
            SetMarginBottom(BalanceRatingContainer, -BalanceRatingBottomMargin);
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    ExpandPanel.Visible = false;
                    _rightPanelAutoCollapsed = false;
                    KeepTerminalUsable();
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;
                    _rightPanelAutoCollapsed = false;

                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                    {
                        RightSide.Visible = false;
                    }

                    SyncTerminalViewport();

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        private void TogglePanel(bool value)
        {
            _rightPanelAutoCollapsed = false;
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
            SyncTerminalViewport();
        }

        private void KeepTerminalUsable()
        {
            if (MainContainer.Width <= 0f)
            {
                SyncTerminalViewport();
                return;
            }

            var insufficientSpace = MainContainer.Width - RightSide.SetWidth < MinimumTerminalColumnWidth;
            if (insufficientSpace && RightSide.Visible)
            {
                RightSide.Visible = false;
                ExpandPanel.Visible = true;
                _rightPanelAutoCollapsed = true;
            }
            else if (!insufficientSpace && _rightPanelAutoCollapsed && DefaultState.Visible)
            {
                RightSide.Visible = true;
                ExpandPanel.Visible = false;
                _rightPanelAutoCollapsed = false;
            }

            SyncTerminalViewport();
        }

        private void SyncTerminalViewport()
        {
            TerminalBackground.ReservedLeftWidth = DefaultState.Visible
                ? MathF.Max(MinimumTerminalColumnWidth, TerminalCard.Width + LeftPanelVisualPadding)
                : 0f;
            TerminalBackground.ReservedRightWidth = RightSide.Visible
                ? MathF.Max(RightSide.SetWidth, RightSide.Width) + RightPanelVisualPadding
                : 0f;
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }
    }
}
