using System;
using Content.Client.Lobby.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Info;

[GenerateTypedNameReferences]
public sealed partial class InfoControlsSection : BoxContainer
{
    public InfoControlsSection()
    {
        RobustXamlLoader.Load(this);
        CrtLobbyTheme.Apply(this, useCrtTypography: false);
    }
}
