using JetBrains.Annotations;
using Content.Client.Lobby.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Guidebook.Controls;

[UsedImplicitly] [GenerateTypedNameReferences]
public sealed partial class GuidebookError : BoxContainer
{
    public GuidebookError()
    {
        RobustXamlLoader.Load(this);
        CrtLobbyTheme.Apply(this, useCrtTypography: false);
    }

    public GuidebookError(string original, string? error) : this()
    {
        Original.AddText(original);

        if (error is not null)
            Error.AddText(error);
    }
}
