using Content.Shared.AU14.Ambassador;
using Content.Shared.AU14.ColonyEconomy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.AU14.Ambassador;

[GenerateTypedNameReferences]
public sealed partial class AmbassadorConsoleWindow : DefaultWindow
{
    public AmbassadorConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(AmbassadorConsoleBuiState s)
    {
        // RuMC edit start
        BudgetLabel.Text = Loc.GetString("au14-ambassador-console-budget", ("amount", s.Budget.ToString("F0")));
        FactionLabel.Text = Loc.GetString("au14-ambassador-console-faction", ("faction", GetLocalizedFactionName(s.FactionName)));
        // RuMC edit end

        // Economy with prices
        EmbargoStatus.Text = s.EmbargoActive
            // RuMC edit start
            ? Loc.GetString("au14-ambassador-console-embargo-active", ("cost", s.EmbargoCostPerMinute.ToString("F0")))
            : Loc.GetString("au14-ambassador-console-embargo-inactive", ("cost", s.EmbargoCostPerMinute.ToString("F0")));
        TradePactStatus.Text = s.TradePactActive
            ? Loc.GetString("au14-ambassador-console-trade-pact-active", ("cost", s.TradePactCostPerMinute.ToString("F0")))
            : Loc.GetString("au14-ambassador-console-trade-pact-inactive", ("cost", s.TradePactCostPerMinute.ToString("F0")));
            // RuMC edit end

        // Comms jam with price
        CommsJamStatus.Text = s.CommsJamActive
            // RuMC edit start
            ? Loc.GetString("au14-ambassador-console-comms-jam-active", ("cost", s.CommsJamCostPerMinute.ToString("F0")))
            : Loc.GetString("au14-ambassador-console-comms-normal", ("cost", s.CommsJamCostPerMinute.ToString("F0")));
            // RuMC edit end

        // Broadcast cost
        BroadcastCostLabel.Text = Loc.GetString("au14-ambassador-console-broadcast-cost", ("cost", s.BroadcastCost.ToString("F0"))); // RuMC edit

        // Signal with prices
        // RuMC edit start
        string signalText;
        if (s.SignalBoostActive) signalText = Loc.GetString("au14-ambassador-console-signal-boost-active", ("cost", s.SignalBoostCostPerMinute.ToString("F0")));
        else if (s.SignalJamActive) signalText = Loc.GetString("au14-ambassador-console-signal-jam-active", ("cost", s.SignalJamCostPerMinute.ToString("F0")));
        else signalText = Loc.GetString("au14-ambassador-console-signal-normal", ("boost", s.SignalBoostCostPerMinute.ToString("F0")), ("jam", s.SignalJamCostPerMinute.ToString("F0")));
        // RuMC edit end
        SignalStatus.Text = signalText;

        // Radar scan button with price
        ScanRadarBtn.Text = Loc.GetString("au14-ambassador-console-scan-radar", ("cost", s.RadarScanCost.ToString("F0"))); // RuMC edit

        // Economy status
        UpdateEconomyStatus(s.EconomyStatus);

        // Update radar list
        RadarList.RemoveAllChildren();
        if (s.RadarList.Count == 0)
        {
            RadarList.AddChild(new Label { Text = Loc.GetString("au14-ambassador-console-no-scan-data") }); // RuMC edit
        }
        else
        {
            foreach (var name in s.RadarList)
            {
                RadarList.AddChild(new Label { Text = Loc.GetString("au14-ambassador-console-radar-entry", ("name", name)) }); // RuMC edit
            }
        }
    }

    private void UpdateEconomyStatus(EconomyStatusState econ)
    {
        EconomyStatusPanel.RemoveAllChildren();
        // RuMC edit start
        EconomyStatusPanel.AddChild(new Label { Text = Loc.GetString("au14-ambassador-console-sales-tax", ("percent", econ.SalesTaxPercent.ToString("F0"))) });
        EconomyStatusPanel.AddChild(new Label { Text = Loc.GetString("au14-ambassador-console-income-tax", ("percent", econ.IncomeTaxPercent.ToString("F0"))) });
        EconomyStatusPanel.AddChild(new Label { Text = Loc.GetString("au14-ambassador-console-transit-tariff", ("percent", econ.TransitTariffPercent.ToString("F0"))) });
        // RuMC edit end

        if (econ.ActiveEmbargoes.Count > 0)
            EconomyStatusPanel.AddChild(new Label { Text = Loc.GetString("au14-ambassador-console-active-embargoes", ("list", string.Join(", ", econ.ActiveEmbargoes))), StyleClasses = { "Caution" } }); // RuMC edit
        else
            EconomyStatusPanel.AddChild(new Label { Text = Loc.GetString("au14-ambassador-console-embargoes-none"), StyleClasses = { "LabelSubText" } }); // RuMC edit

        if (econ.ActiveTradePacts.Count > 0)
            EconomyStatusPanel.AddChild(new Label { Text = Loc.GetString("au14-ambassador-console-active-trade-pacts", ("list", string.Join(", ", econ.ActiveTradePacts))) }); // RuMC edit
        else
            EconomyStatusPanel.AddChild(new Label { Text = Loc.GetString("au14-ambassador-console-trade-pacts-none"), StyleClasses = { "LabelSubText" } }); // RuMC edit
    }

    // RuMC edit start
    private static string GetLocalizedFactionName(string factionName)
    {
        var key = $"au14-ambassador-console-faction-name-{factionName.ToLower().Replace(" ", "-")}";
        return Loc.TryGetString(key, out var localized) ? localized : factionName;
    }
    // RuMC edit end
}
