name: No submodule update checker

on:
  pull_request:
    paths:
      - 'RobustToolbox'

permissions:
  contents: read

jobs:
  this_aint_right:
    name: Submodule update in pr found
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: exit 1
